### ISSUE TITLE
[Question] Unreal marketplace 

### ISSUE THREAD

**Issue by pwnpwn** [PlayFab/UnrealBlueprintSDK#43]
Hi!
I can see in one of your recent commits that you are preparing to release on the unreal marketplace. Is this submitted already and when can we expect to see a plugin in the launcher?

**Comment by pgilmorepf** [comment]
We have already done the first stage submission to Unreal.  PlayFab hasn't received a response from Unreal yet.  I plan to follow up on that today, but the timing (and acceptance) is out of my hands.

Thanks for your interest.  I'm going to close the issue, but I'm definitely still pushing for this.  :)

**Comment by pwnpwn** [comment]
Great to know that things are moving, now I know this is something worth keeping an eye on. Thank you!
