### ISSUE TITLE
Client Content Example getting 1074 error

### ISSUE THREAD

**Issue by intoxicat3** [PlayFab/UnrealBlueprintSDK#9]
Repro:
- Use UnrealBlueprintSDK-master
- Open Client Example Project (PlayFabClientSDK),
- Register user,
- Login user,
- Try to get CloudURL - you will get 1074 error.

Using UE 4.10.2 on Windows 10.

**Comment by pgilmorepf** [comment]
Unreal doesn't have patch notes yet, as we still consider this SDK to be in Beta.
However, this issue was found and fixed Jan 25:
https://github.com/PlayFab/UnrealBlueprintSDK/commit/bbae7183fe088ee3f5ca1dff84dafff986b55571
